/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package AgendaCRUD;

import Banco.AgendaDAO;
import com.google.protobuf.TextFormat.ParseException;
import java.awt.HeadlessException;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.time.format.DateTimeParseException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.MaskFormatter;

/**
 *
 * @author Reges
 */
public class Principal extends javax.swing.JFrame {

    private AgendaDAO agendaDAO;
    private String emailER = "^[\\w-\\+]+(\\.[\\w]+)*@[\\w-]+(\\.[\\w]+)*(\\.[a-z]{2,})$";
    
    public Principal() {
        initComponents();
        this.agendaDAO = new AgendaDAO();
        
    }
    
    public void validaEmail(String e){
        e.matches(emailER);
        
        if(e.matches(emailER)){
            txtValidaEmail.setText("Valido");            
        }else{
            txtValidaEmail.setText("Invalido");
        }
    }
    
     public String formataData(String data){
        DateTimeFormatter formato = DateTimeFormatter.ofPattern("dd/MM/yyyy"); 
        LocalDate dataJ = LocalDate.parse(data, formato); 
        formato.format(dataJ); 
        
        return formato.format(dataJ);
    }
    
    public String formataTelefone(String mascara, String valor){
        MaskFormatter mask = null;
        String resultado = "";
        try {
            mask = new MaskFormatter(mascara);
        } catch (java.text.ParseException ex) {
             ex.printStackTrace();
        }
        mask.setValueContainsLiteralCharacters(false);
        mask.setPlaceholderCharacter('_');
        try {
            resultado = mask.valueToString(valor);
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        return resultado;
    }
     
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane2 = new javax.swing.JTabbedPane();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        txtSobrenome = new javax.swing.JTextField();
        txtNascimento = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtRotEmail = new javax.swing.JTextField();
        txtTel = new javax.swing.JTextField();
        txtRotTel = new javax.swing.JTextField();
        btnCadastrar = new javax.swing.JButton();
        btnLimpar = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        btnValidaEmail = new javax.swing.JButton();
        txtValidaEmail = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        txtValidaNascimento = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblContatos = new javax.swing.JTable();
        btnCarregar = new javax.swing.JButton();
        btnRemover = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtFiltroNome = new javax.swing.JTextField();
        btnFiltrar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblPesquisa = new javax.swing.JTable();
        jLabel14 = new javax.swing.JLabel();
        txtFiltroID = new javax.swing.JTextField();
        btnFiltroId = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        txtAlteraNome = new javax.swing.JTextField();
        btnAlteraNome = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblEditar = new javax.swing.JTable();
        btnAtualizarEditar = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        btnAlteraEmail = new javax.swing.JButton();
        txtAlteraEmail = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        txtAlteraTel = new javax.swing.JTextField();
        btnAlteraTel = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        txtAlteraSobrenome = new javax.swing.JTextField();
        btnAlteraSobrenome = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        txtAlteraRotEmail = new javax.swing.JTextField();
        btnAlteraRotEmail = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        txtAlteraRotTel = new javax.swing.JTextField();
        btnAlteraRotTel = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        txtAlteraNascimento = new javax.swing.JTextField();
        btnAlteraNascimento = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Agenda 3000");

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.setText("** A agenda eletrônica mais completa do mercado **\nCom incríveis recursos de:\n- Minimizar, ao clicar no ícone de minimizar\n- Fechar, ao clicar no ícone de fechar \n- E exclusivamente e únicamente, de causar\npesadelos ao maximar.");
        jTextArea1.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextArea1.setEnabled(false);
        jTextArea1.setHighlighter(null);
        jTextArea1.setOpaque(false);
        jScrollPane3.setViewportView(jTextArea1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(291, 291, 291)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(219, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(194, 194, 194))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(142, 142, 142)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(164, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Agenda", jPanel1);

        jPanel3.setEnabled(false);
        jPanel3.setFocusable(false);
        jPanel3.setOpaque(false);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Adicionar Contato");

        jLabel3.setText("Nome Completo");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel4.setText("Sobrenome");

        jLabel5.setText("Data de Nascimento");

        jLabel6.setText("Email");

        jLabel7.setText("Rotulo do Email");

        jLabel8.setText("Telefone");

        jLabel9.setText("Rotulo do Telefone");

        txtNascimento.setToolTipText("");
        txtNascimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNascimentoActionPerformed(evt);
            }
        });

        txtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });

        txtRotEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRotEmailActionPerformed(evt);
            }
        });

        btnCadastrar.setText("Cadastrar");
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });

        btnLimpar.setText("Limpar");
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel10.setText("Nome");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel11.setText("Ex: 00/00/0000");

        btnValidaEmail.setText("Validar");
        btnValidaEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnValidaEmailActionPerformed(evt);
            }
        });

        txtValidaEmail.setEditable(false);
        txtValidaEmail.setText(" ");
        txtValidaEmail.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtValidaEmail.setEnabled(false);
        txtValidaEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtValidaEmailActionPerformed(evt);
            }
        });

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 9)); // NOI18N
        jLabel22.setText("Ex: ###########");

        txtValidaNascimento.setEditable(false);
        txtValidaNascimento.setText(" ");
        txtValidaNascimento.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtValidaNascimento.setDragEnabled(true);
        txtValidaNascimento.setEnabled(false);
        txtValidaNascimento.setOpaque(false);
        txtValidaNascimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtValidaNascimentoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(288, 288, 288))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(164, 164, 164)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(18, 18, 18)
                                .addComponent(txtRotEmail))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(35, 35, 35)
                        .addComponent(btnValidaEmail)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtValidaEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(btnCadastrar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnLimpar))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addGap(18, 18, 18)
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(18, 18, 18)
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtSobrenome, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                    .addComponent(jLabel5)
                                    .addGap(18, 18, 18)
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                            .addComponent(txtNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(txtValidaNascimento))))))
                        .addGap(97, 97, 97))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                            .addComponent(jLabel9)
                            .addGap(18, 18, 18)
                            .addComponent(txtRotTel))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                            .addComponent(jLabel8)
                            .addGap(18, 18, 18)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtTel, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(117, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSobrenome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtValidaNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnValidaEmail)
                    .addComponent(txtValidaEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtRotEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtTel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1)
                .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtRotTel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCadastrar)
                    .addComponent(btnLimpar))
                .addGap(49, 49, 49))
        );

        jTabbedPane1.addTab("Adicionar", jPanel3);

        tblContatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nome", "Sobrenome", "Nascimento", "Email", "Rot. Email", "Telefone", "Rot. Tel."
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblContatos);

        btnCarregar.setText("Atualizar");
        btnCarregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCarregarActionPerformed(evt);
            }
        });

        btnRemover.setText("Excluir");
        btnRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 789, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(btnCarregar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnRemover)
                .addGap(20, 20, 20))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCarregar)
                    .addComponent(btnRemover))
                .addGap(59, 59, 59))
        );

        jTabbedPane1.addTab("Listar", jPanel4);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel12.setText("Procurar");

        jLabel13.setText("Pesquisar Nome");

        txtFiltroNome.setText(" ");
        txtFiltroNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFiltroNomeActionPerformed(evt);
            }
        });

        btnFiltrar.setText("Pesquisar");
        btnFiltrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFiltrarActionPerformed(evt);
            }
        });

        tblPesquisa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nome", "Sobrenome", "Data Nascimento", "Email", "Rot. Email", "Telefone", "Rot. Tel"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblPesquisa);

        jLabel14.setText("Pesquisar ID");

        txtFiltroID.setText(" ");

        btnFiltroId.setText("Pesquisar");
        btnFiltroId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFiltroIdActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 769, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtFiltroNome)
                            .addComponent(txtFiltroID, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE))
                        .addGap(41, 41, 41)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnFiltrar)
                            .addComponent(jLabel12)
                            .addComponent(btnFiltroId))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel12)
                .addGap(34, 34, 34)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(txtFiltroNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnFiltrar))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(txtFiltroID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnFiltroId))
                .addGap(26, 26, 26)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(141, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Procurar", jPanel2);

        jLabel15.setText("Nome");

        txtAlteraNome.setText(" ");
        txtAlteraNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAlteraNomeActionPerformed(evt);
            }
        });

        btnAlteraNome.setText("Editar");
        btnAlteraNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlteraNomeActionPerformed(evt);
            }
        });

        tblEditar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nome", "Sobrenome", "Nascimento", "Email", "Rot. Email", "Telefone", "Rot. Tel."
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblEditar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblEditarMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tblEditar);

        btnAtualizarEditar.setText("Atualizar");
        btnAtualizarEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtualizarEditarActionPerformed(evt);
            }
        });

        jLabel16.setText("Email");

        btnAlteraEmail.setText("Editar");
        btnAlteraEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlteraEmailActionPerformed(evt);
            }
        });

        txtAlteraEmail.setText(" ");

        jLabel17.setText("Telefone");

        txtAlteraTel.setText(" ");
        txtAlteraTel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAlteraTelActionPerformed(evt);
            }
        });

        btnAlteraTel.setText("Editar");
        btnAlteraTel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlteraTelActionPerformed(evt);
            }
        });

        jLabel18.setText("Sobrenome");

        txtAlteraSobrenome.setText(" ");

        btnAlteraSobrenome.setText("Editar");
        btnAlteraSobrenome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlteraSobrenomeActionPerformed(evt);
            }
        });

        jLabel19.setText("Rot. Email");

        txtAlteraRotEmail.setText(" ");
        txtAlteraRotEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAlteraRotEmailActionPerformed(evt);
            }
        });

        btnAlteraRotEmail.setText("Editar");
        btnAlteraRotEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlteraRotEmailActionPerformed(evt);
            }
        });

        jLabel20.setText("Rot. Tel.");

        txtAlteraRotTel.setText(" ");

        btnAlteraRotTel.setText("Editar");
        btnAlteraRotTel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlteraRotTelActionPerformed(evt);
            }
        });

        jLabel21.setText("Nascimento");

        txtAlteraNascimento.setText(" ");

        btnAlteraNascimento.setText("Editar");
        btnAlteraNascimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlteraNascimentoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 769, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAtualizarEditar)
                .addGap(29, 29, 29))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel21)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtAlteraNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel5Layout.createSequentialGroup()
                                    .addComponent(jLabel17)
                                    .addGap(23, 23, 23)
                                    .addComponent(txtAlteraTel, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel5Layout.createSequentialGroup()
                                    .addComponent(jLabel15)
                                    .addGap(38, 38, 38)
                                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtAlteraEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtAlteraNome, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(jLabel16))
                        .addGap(42, 42, 42)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnAlteraNome)
                            .addComponent(btnAlteraTel)
                            .addComponent(btnAlteraNascimento)
                            .addComponent(btnAlteraEmail))
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(46, 46, 46)
                                .addComponent(jLabel18)
                                .addGap(18, 18, 18)
                                .addComponent(txtAlteraSobrenome)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnAlteraSobrenome))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(52, 52, 52)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel19)
                                    .addComponent(jLabel20))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtAlteraRotTel)
                                    .addComponent(txtAlteraRotEmail))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnAlteraRotEmail, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnAlteraRotTel, javax.swing.GroupLayout.Alignment.TRAILING))))
                        .addGap(26, 26, 26))))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(txtAlteraNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAlteraNome)
                    .addComponent(jLabel18)
                    .addComponent(txtAlteraSobrenome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAlteraSobrenome))
                .addGap(23, 23, 23)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel16)
                        .addComponent(txtAlteraEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnAlteraEmail))
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel19)
                        .addComponent(txtAlteraRotEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnAlteraRotEmail)))
                .addGap(24, 24, 24)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel17)
                        .addComponent(txtAlteraTel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnAlteraTel))
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel20)
                        .addComponent(txtAlteraRotTel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnAlteraRotTel)))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel21)
                        .addComponent(txtAlteraNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnAlteraNascimento))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnAtualizarEditar)
                .addGap(68, 68, 68))
        );

        jTabbedPane1.addTab("Editar", jPanel5);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
        String nome = txtNome.getText();
        String sobrenome = txtSobrenome.getText();
        String nascimento = txtNascimento.getText();
        String email = txtEmail.getText();
        String rotEmail = txtRotEmail.getText();
        String tel = txtTel.getText();
        String rotTel = txtRotTel.getText();
    
        Principal p = new Principal();
        if(email.matches(emailER)){
            try{
                Agenda agenda = new Agenda(nome, sobrenome, formataData(nascimento), email, rotEmail, p.formataTelefone("(##) #####-####", tel), rotTel);
                JOptionPane.showMessageDialog (this, "Cadastro efetuado");
                agendaDAO.inserir(agenda);
                txtValidaNascimento.setText("Válido");
            }catch(DateTimeParseException dt){
                txtValidaNascimento.setText("Inválido");
                JOptionPane.showMessageDialog(this, "Data de nascimento inválida.");
            }
        }else{
            JOptionPane.showMessageDialog(this, "Email inválido.");
        }  
    }//GEN-LAST:event_btnCadastrarActionPerformed

    private void txtNascimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNascimentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNascimentoActionPerformed

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailActionPerformed

    private void btnCarregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCarregarActionPerformed
        String[] campos = {"ID","Nome","Sobrenome","Data Nascimento","Email","Rot. Email","Telefone","Rot. Tel"};
        DefaultTableModel dtm = new DefaultTableModel(campos,0);
        this.tblContatos.setModel(dtm);

        List<Agenda> contatos = this.agendaDAO.consultarContatos();
                 
        for(int i = 0; i < contatos.size(); i++){
            Agenda a = contatos.get(i);          
            String[] valores = {Integer.toString(a.getId()),a.getNome(), a.getSobrenome(), a.getNascimento(), a.getEmail(), a.getRotuloEmail(), a.getTelefone(), a.getRotuloTelefone()};
            dtm.addRow(valores);
        }
    }//GEN-LAST:event_btnCarregarActionPerformed

    private void btnRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoverActionPerformed
        int linhaSelecionada = this.tblContatos.getSelectedRow();
                
        String id = (String)this.tblContatos.getValueAt(linhaSelecionada, 0);
        
        this.agendaDAO.remover(Integer.parseInt(id));
                
        this.btnCarregarActionPerformed(evt);
    }//GEN-LAST:event_btnRemoverActionPerformed

    private void btnFiltrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFiltrarActionPerformed
        String[] campos = {"ID","Nome","Sobrenome","Data Nascimento","Email","Rot. Email","Telefone","Rot. Tel"};
        DefaultTableModel dtm = new DefaultTableModel(campos,0);
        this.tblPesquisa.setModel(dtm);
        
        String filtronome = txtFiltroNome.getText();
        List<Agenda> contatos = this.agendaDAO.consultarContatosPorNome(filtronome);
        
        for(int i = 0; i < contatos.size(); i++){
            Agenda a = contatos.get(i);

            String[] valores = {Integer.toString(a.getId()),a.getNome(), a.getSobrenome(), a.getNascimento(), a.getEmail(), a.getRotuloEmail(), a.getTelefone(), a.getRotuloTelefone()};
            dtm.addRow(valores);
        }

        txtFiltroNome.setText(null);        
    }//GEN-LAST:event_btnFiltrarActionPerformed

    private void txtFiltroNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFiltroNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFiltroNomeActionPerformed

    private void btnFiltroIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFiltroIdActionPerformed
        String[] campos = {"ID","Nome","Sobrenome","Data Nascimento","Email","Rot. Email","Telefone","Rot. Tel"};
        DefaultTableModel dtm = new DefaultTableModel(campos,0);
        this.tblPesquisa.setModel(dtm);
        
        String id = txtFiltroID.getText();  
        
        List <Agenda> contatos = this.agendaDAO.consultarContatoId(id);
        
        for(int i = 0; i < contatos.size(); i++){
            Agenda a = contatos.get(i);
            
            String[] valores = {Integer.toString(a.getId()),a.getNome(), a.getSobrenome(), a.getNascimento(), a.getEmail(), a.getRotuloEmail(), a.getTelefone(), a.getRotuloTelefone()};
            dtm.addRow(valores);
        }
        
        txtFiltroID.setText(null);
    }//GEN-LAST:event_btnFiltroIdActionPerformed

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        txtNome.setText(null);
        txtEmail.setText(null);
        txtNascimento.setText(null);
        txtRotEmail.setText(null);
        txtRotTel.setText(null);
        txtSobrenome.setText(null);
        txtTel.setText(null);
    }//GEN-LAST:event_btnLimparActionPerformed

    private void btnAlteraNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlteraNomeActionPerformed
        int linhaSelecionada = this.tblEditar.getSelectedRow();        
        String id = (String)this.tblEditar.getValueAt(linhaSelecionada, 0);
        
        
        String nome = this.txtAlteraNome.getText();
                
        Agenda agenda = new Agenda();
        
        agenda.setNome(nome);
        agenda.setId(Integer.parseInt(id));
        
        agendaDAO.atualizarNome(agenda);
        
        JOptionPane.showMessageDialog(this, "Nome alterado. Pressione atualizar");
        
        this.btnCarregarActionPerformed(evt);
    }//GEN-LAST:event_btnAlteraNomeActionPerformed

    private void btnAtualizarEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtualizarEditarActionPerformed
        String[] campos = {"ID","Nome","Sobrenome","Data Nascimento","Email","Rot. Email","Telefone","Rot. Tel"};
        DefaultTableModel dtm = new DefaultTableModel(campos,0);
        this.tblEditar.setModel(dtm);

        List<Agenda> contatos = this.agendaDAO.consultarContatos();
                 
        for(int i = 0; i < contatos.size(); i++){
            Agenda a = contatos.get(i);          
            String[] valores = {Integer.toString(a.getId()),a.getNome(), a.getSobrenome(), a.getNascimento(), a.getEmail(), a.getRotuloEmail(), a.getTelefone(), a.getRotuloTelefone()};
            dtm.addRow(valores);
        }
        txtAlteraNome.setText(null);
        txtAlteraSobrenome.setText(null);
        txtAlteraNascimento.setText(null);
        txtAlteraEmail.setText(null);
        txtAlteraRotEmail.setText(null);
        txtAlteraTel.setText(null);
        txtAlteraRotTel.setText(null);
    }//GEN-LAST:event_btnAtualizarEditarActionPerformed

    private void tblEditarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblEditarMouseClicked
        int linhaSelecionada = this.tblEditar.getSelectedRow();
        
        String id = (String)this.tblEditar.getValueAt(linhaSelecionada, 0);
        String nome = (String)this.tblEditar.getValueAt(linhaSelecionada, 1);
        String sobrenome = (String)this.tblEditar.getValueAt(linhaSelecionada, 2);
        String nascimento = (String)this.tblEditar.getValueAt(linhaSelecionada, 3);
        String email = (String)this.tblEditar.getValueAt(linhaSelecionada, 4);
        String rotEmail = (String)this.tblEditar.getValueAt(linhaSelecionada, 5);
        String telefone = (String)this.tblEditar.getValueAt(linhaSelecionada, 6);
        String rotTel = (String)this.tblEditar.getValueAt(linhaSelecionada, 7);
        
        txtAlteraNome.setText(nome);
        txtAlteraSobrenome.setText(sobrenome);
        txtAlteraNascimento.setText(nascimento);
        txtAlteraEmail.setText(email);
        txtAlteraRotEmail.setText(rotEmail);
        txtAlteraTel.setText(telefone);
        txtAlteraRotTel.setText(rotTel);
    }//GEN-LAST:event_tblEditarMouseClicked

    private void txtAlteraRotEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAlteraRotEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAlteraRotEmailActionPerformed

    private void txtAlteraTelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAlteraTelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAlteraTelActionPerformed

    private void btnAlteraSobrenomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlteraSobrenomeActionPerformed
        int linhaSelecionada = this.tblEditar.getSelectedRow();        
        String id = (String)this.tblEditar.getValueAt(linhaSelecionada, 0);
        
        
        String sobrenome = this.txtAlteraSobrenome.getText();
                
        Agenda agenda = new Agenda();
        
        agenda.setSobrenome(sobrenome);
        agenda.setId(Integer.parseInt(id));
        
        agendaDAO.atualizarSobrenome(agenda);
        
        JOptionPane.showMessageDialog(this, "Sobrenome alterado. Pressione atualizar");
        
        this.btnCarregarActionPerformed(evt);
    }//GEN-LAST:event_btnAlteraSobrenomeActionPerformed

    private void btnAlteraEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlteraEmailActionPerformed
        int linhaSelecionada = this.tblEditar.getSelectedRow();        
        String id = (String)this.tblEditar.getValueAt(linhaSelecionada, 0);
 
        String email = this.txtAlteraEmail.getText();
        Agenda agenda = new Agenda();
        
        if(email.matches(emailER)){
            
            agenda.setEmail(email);
            agenda.setId(Integer.parseInt(id));
        
            agendaDAO.atualizarEmail(agenda);
        
            JOptionPane.showMessageDialog(this, "Email alterado. Pressione atualizar");
            
            this.btnCarregarActionPerformed(evt);
        }else{
            txtValidaEmail.setText("Invalido");
            JOptionPane.showMessageDialog(this, "Email inválido.");
        }  
    }//GEN-LAST:event_btnAlteraEmailActionPerformed

    private void btnAlteraRotEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlteraRotEmailActionPerformed
        int linhaSelecionada = this.tblEditar.getSelectedRow();        
        String id = (String)this.tblEditar.getValueAt(linhaSelecionada, 0);
        
        
        String rotEmail = this.txtAlteraRotEmail.getText();
                
        Agenda agenda = new Agenda();
        
        agenda.setRotuloEmail(rotEmail);
        agenda.setId(Integer.parseInt(id));
        
        agendaDAO.atualizarRotEmail(agenda);
        
        JOptionPane.showMessageDialog(this, "Rotulo do e-mail alterado. Pressione atualizar");
        
        this.btnCarregarActionPerformed(evt);
    }//GEN-LAST:event_btnAlteraRotEmailActionPerformed

    private void btnAlteraTelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlteraTelActionPerformed
        int linhaSelecionada = this.tblEditar.getSelectedRow();        
        String id = (String)this.tblEditar.getValueAt(linhaSelecionada, 0);
        
        
        String telefone = this.txtAlteraTel.getText();
        
        String armazenaTel = formataTelefone("(##) #####-####", telefone);
        
        Agenda agenda = new Agenda();
        
        agenda.setTelefone(armazenaTel);
        agenda.setId(Integer.parseInt(id));
        agendaDAO.atualizarTelefone(agenda);
        JOptionPane.showMessageDialog(this, "Telefone alterado. Pressione atualizar");
        this.btnCarregarActionPerformed(evt);
    }//GEN-LAST:event_btnAlteraTelActionPerformed

    private void btnAlteraRotTelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlteraRotTelActionPerformed
        int linhaSelecionada = this.tblEditar.getSelectedRow();        
        String id = (String)this.tblEditar.getValueAt(linhaSelecionada, 0);
        
        
        String rotTel = this.txtAlteraRotTel.getText();
                
        Agenda agenda = new Agenda();
        
        agenda.setRotuloTelefone(rotTel);
        agenda.setId(Integer.parseInt(id));
        
        agendaDAO.atualizarRotTelefone(agenda);
        
        JOptionPane.showMessageDialog(this, "Rotulo do telefone alterado. Pressione atualizar");
        
        this.btnCarregarActionPerformed(evt);
    }//GEN-LAST:event_btnAlteraRotTelActionPerformed

    private void btnAlteraNascimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlteraNascimentoActionPerformed
        int linhaSelecionada = this.tblEditar.getSelectedRow();        
        String id = (String)this.tblEditar.getValueAt(linhaSelecionada, 0);
        
        
        String nascimento = this.txtAlteraNascimento.getText();
                
        Agenda agenda = new Agenda();
                
        try{
            agenda.setNascimento(formataData(nascimento));
        
            agenda.setId(Integer.parseInt(id));

            agendaDAO.atualizarNascimento(agenda);

            JOptionPane.showMessageDialog(this, "Data de nascimento alterado. Pressione atualizar");

            this.btnCarregarActionPerformed(evt);
        }catch(DateTimeParseException dt){
            JOptionPane.showMessageDialog(this, "Data de nascimento inválida.");
        }
    }//GEN-LAST:event_btnAlteraNascimentoActionPerformed

    private void txtRotEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRotEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRotEmailActionPerformed

    private void btnValidaEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnValidaEmailActionPerformed
        String email = txtEmail.getText();
        validaEmail(email);        
    }//GEN-LAST:event_btnValidaEmailActionPerformed

    private void txtValidaEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtValidaEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtValidaEmailActionPerformed

    private void txtAlteraNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAlteraNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAlteraNomeActionPerformed

    private void txtValidaNascimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtValidaNascimentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtValidaNascimentoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlteraEmail;
    private javax.swing.JButton btnAlteraNascimento;
    private javax.swing.JButton btnAlteraNome;
    private javax.swing.JButton btnAlteraRotEmail;
    private javax.swing.JButton btnAlteraRotTel;
    private javax.swing.JButton btnAlteraSobrenome;
    private javax.swing.JButton btnAlteraTel;
    private javax.swing.JButton btnAtualizarEditar;
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JButton btnCarregar;
    private javax.swing.JButton btnFiltrar;
    private javax.swing.JButton btnFiltroId;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JButton btnRemover;
    private javax.swing.JButton btnValidaEmail;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTable tblContatos;
    private javax.swing.JTable tblEditar;
    private javax.swing.JTable tblPesquisa;
    private javax.swing.JTextField txtAlteraEmail;
    private javax.swing.JTextField txtAlteraNascimento;
    private javax.swing.JTextField txtAlteraNome;
    private javax.swing.JTextField txtAlteraRotEmail;
    private javax.swing.JTextField txtAlteraRotTel;
    private javax.swing.JTextField txtAlteraSobrenome;
    private javax.swing.JTextField txtAlteraTel;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtFiltroID;
    private javax.swing.JTextField txtFiltroNome;
    private javax.swing.JTextField txtNascimento;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtRotEmail;
    private javax.swing.JTextField txtRotTel;
    private javax.swing.JTextField txtSobrenome;
    private javax.swing.JTextField txtTel;
    private javax.swing.JTextField txtValidaEmail;
    private javax.swing.JTextField txtValidaNascimento;
    // End of variables declaration//GEN-END:variables
}
